# Setup
title:               Machine Learning for Big Code and Naturalness
tagline:             'a living literature review'
description:         'Research on machine learning for source code.'
url:                 https://celinelee-intel.github.io
baseurl:             https://celinelee-intel.github.io/celinelee-intel/

collections:
  publications:
    output: true
    permalink: /:collection/:path/

plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
    style: compressed
