# Setup
title:               Machine Programming
tagline:             'a living literature review'
description:         'Research on machine programming.'
url:                 https://celinelee-intel.github.io/celinelee-intel/
baseurl:             https://celinelee-intel.github.io/celinelee-intel/

collections:
  publications:
    output: true
    permalink: /:collection/:path/

plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
    style: compressed
